# Generated by Django 6.0.2 on 2026-02-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_approved_at_order_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_confirmed_by_customer',
            field=models.BooleanField(default=False),
        ),
    ]
