# Generated by Django 6.0.2 on 2026-02-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_cancellation_request_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='orders/refunds/'),
        ),
    ]
