# Generated by Django 6.0.2 on 2026-02-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_refund_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_made_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
